//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 01:14:19 PM IST 
//


package com.model.configurationJenkins;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for com.coravy.hudson.plugins.github.GithubProjectPropertyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="com.coravy.hudson.plugins.github.GithubProjectPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="projectUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="plugin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.coravy.hudson.plugins.github.GithubProjectPropertyType", propOrder = {
        "projectUrl",
        "displayName"
})
public class ComCoravyHudsonPluginsGithubGithubProjectPropertyType {

    @XmlElement(required = true)
    protected String projectUrl;
    @XmlElement(required = true)
    protected String displayName;
    @XmlAttribute(name = "plugin")
    protected String plugin;

    /**
     * Gets the value of the projectUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProjectUrl() {
        return projectUrl;
    }

    /**
     * Sets the value of the projectUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProjectUrl(String value) {
        this.projectUrl = value;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the plugin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * Sets the value of the plugin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlugin(String value) {
        this.plugin = value;
    }

}
