//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 01:14:19 PM IST 
//


package com.model.configurationJenkins;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for org.jenkinsci.plugins.ghprb.GhprbTriggerType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="org.jenkinsci.plugins.ghprb.GhprbTriggerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="spec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="configVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adminlist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allowMembersOfWhitelistedOrgsAsAdmin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orgslist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cron" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildDescTemplate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="onlyTriggerPhrase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="useGitHubHooks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="permitAll" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="whitelist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="autoCloseFailedPullRequests" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayBuildErrorsOnDownstreamBuilds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="whiteListTargetBranches" type="{}whiteListTargetBranchesType"/>
 *         &lt;element name="blackListTargetBranches" type="{}blackListTargetBranchesType"/>
 *         &lt;element name="gitHubAuthId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="triggerPhrase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="skipBuildPhrase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blackListCommitAuthor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blackListLabels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="whiteListLabels" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="includedRegions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="excludedRegions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="extensions" type="{}extensionsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="plugin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "org.jenkinsci.plugins.ghprb.GhprbTriggerType", propOrder = {
        "spec",
        "configVersion",
        "adminlist",
        "allowMembersOfWhitelistedOrgsAsAdmin",
        "orgslist",
        "cron",
        "buildDescTemplate",
        "onlyTriggerPhrase",
        "useGitHubHooks",
        "permitAll",
        "whitelist",
        "autoCloseFailedPullRequests",
        "displayBuildErrorsOnDownstreamBuilds",
        "whiteListTargetBranches",
        "blackListTargetBranches",
        "gitHubAuthId",
        "triggerPhrase",
        "skipBuildPhrase",
        "blackListCommitAuthor",
        "blackListLabels",
        "whiteListLabels",
        "includedRegions",
        "excludedRegions",
        "extensions"
})
public class OrgJenkinsciPluginsGhprbGhprbTriggerType {

    @XmlElement(required = true)
    protected String spec;
    @XmlElement(required = true)
    protected String configVersion;
    @XmlElement(required = true)
    protected String adminlist;
    @XmlElement(required = true)
    protected String allowMembersOfWhitelistedOrgsAsAdmin;
    @XmlElement(required = true)
    protected String orgslist;
    @XmlElement(required = true)
    protected String cron;
    @XmlElement(required = true)
    protected String buildDescTemplate;
    @XmlElement(required = true)
    protected String onlyTriggerPhrase;
    @XmlElement(required = true)
    protected String useGitHubHooks;
    @XmlElement(required = true)
    protected String permitAll;
    @XmlElement(required = true)
    protected String whitelist;
    @XmlElement(required = true)
    protected String autoCloseFailedPullRequests;
    @XmlElement(required = true)
    protected String displayBuildErrorsOnDownstreamBuilds;
    @XmlElement(required = true)
    protected WhiteListTargetBranchesType whiteListTargetBranches;
    @XmlElement(required = true)
    protected BlackListTargetBranchesType blackListTargetBranches;
    @XmlElement(required = true)
    protected String gitHubAuthId;
    @XmlElement(required = true)
    protected String triggerPhrase;
    @XmlElement(required = true)
    protected String skipBuildPhrase;
    @XmlElement(required = true)
    protected String blackListCommitAuthor;
    @XmlElement(required = true)
    protected String blackListLabels;
    @XmlElement(required = true)
    protected String whiteListLabels;
    @XmlElement(required = true)
    protected String includedRegions;
    @XmlElement(required = true)
    protected String excludedRegions;
    @XmlElement(required = true)
    protected ExtensionsType extensions;
    @XmlAttribute(name = "plugin")
    protected String plugin;

    /**
     * Gets the value of the spec property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSpec() {
        return spec;
    }

    /**
     * Sets the value of the spec property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSpec(String value) {
        this.spec = value;
    }

    /**
     * Gets the value of the configVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConfigVersion() {
        return configVersion;
    }

    /**
     * Sets the value of the configVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConfigVersion(String value) {
        this.configVersion = value;
    }

    /**
     * Gets the value of the adminlist property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAdminlist() {
        return adminlist;
    }

    /**
     * Sets the value of the adminlist property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAdminlist(String value) {
        this.adminlist = value;
    }

    /**
     * Gets the value of the allowMembersOfWhitelistedOrgsAsAdmin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAllowMembersOfWhitelistedOrgsAsAdmin() {
        return allowMembersOfWhitelistedOrgsAsAdmin;
    }

    /**
     * Sets the value of the allowMembersOfWhitelistedOrgsAsAdmin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAllowMembersOfWhitelistedOrgsAsAdmin(String value) {
        this.allowMembersOfWhitelistedOrgsAsAdmin = value;
    }

    /**
     * Gets the value of the orgslist property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrgslist() {
        return orgslist;
    }

    /**
     * Sets the value of the orgslist property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrgslist(String value) {
        this.orgslist = value;
    }

    /**
     * Gets the value of the cron property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCron() {
        return cron;
    }

    /**
     * Sets the value of the cron property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCron(String value) {
        this.cron = value;
    }

    /**
     * Gets the value of the buildDescTemplate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBuildDescTemplate() {
        return buildDescTemplate;
    }

    /**
     * Sets the value of the buildDescTemplate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBuildDescTemplate(String value) {
        this.buildDescTemplate = value;
    }

    /**
     * Gets the value of the onlyTriggerPhrase property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOnlyTriggerPhrase() {
        return onlyTriggerPhrase;
    }

    /**
     * Sets the value of the onlyTriggerPhrase property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOnlyTriggerPhrase(String value) {
        this.onlyTriggerPhrase = value;
    }

    /**
     * Gets the value of the useGitHubHooks property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUseGitHubHooks() {
        return useGitHubHooks;
    }

    /**
     * Sets the value of the useGitHubHooks property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUseGitHubHooks(String value) {
        this.useGitHubHooks = value;
    }

    /**
     * Gets the value of the permitAll property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPermitAll() {
        return permitAll;
    }

    /**
     * Sets the value of the permitAll property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPermitAll(String value) {
        this.permitAll = value;
    }

    /**
     * Gets the value of the whitelist property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWhitelist() {
        return whitelist;
    }

    /**
     * Sets the value of the whitelist property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWhitelist(String value) {
        this.whitelist = value;
    }

    /**
     * Gets the value of the autoCloseFailedPullRequests property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAutoCloseFailedPullRequests() {
        return autoCloseFailedPullRequests;
    }

    /**
     * Sets the value of the autoCloseFailedPullRequests property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAutoCloseFailedPullRequests(String value) {
        this.autoCloseFailedPullRequests = value;
    }

    /**
     * Gets the value of the displayBuildErrorsOnDownstreamBuilds property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDisplayBuildErrorsOnDownstreamBuilds() {
        return displayBuildErrorsOnDownstreamBuilds;
    }

    /**
     * Sets the value of the displayBuildErrorsOnDownstreamBuilds property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisplayBuildErrorsOnDownstreamBuilds(String value) {
        this.displayBuildErrorsOnDownstreamBuilds = value;
    }

    /**
     * Gets the value of the whiteListTargetBranches property.
     *
     * @return possible object is
     * {@link WhiteListTargetBranchesType }
     */
    public WhiteListTargetBranchesType getWhiteListTargetBranches() {
        return whiteListTargetBranches;
    }

    /**
     * Sets the value of the whiteListTargetBranches property.
     *
     * @param value allowed object is
     *              {@link WhiteListTargetBranchesType }
     */
    public void setWhiteListTargetBranches(WhiteListTargetBranchesType value) {
        this.whiteListTargetBranches = value;
    }

    /**
     * Gets the value of the blackListTargetBranches property.
     *
     * @return possible object is
     * {@link BlackListTargetBranchesType }
     */
    public BlackListTargetBranchesType getBlackListTargetBranches() {
        return blackListTargetBranches;
    }

    /**
     * Sets the value of the blackListTargetBranches property.
     *
     * @param value allowed object is
     *              {@link BlackListTargetBranchesType }
     */
    public void setBlackListTargetBranches(BlackListTargetBranchesType value) {
        this.blackListTargetBranches = value;
    }

    /**
     * Gets the value of the gitHubAuthId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGitHubAuthId() {
        return gitHubAuthId;
    }

    /**
     * Sets the value of the gitHubAuthId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGitHubAuthId(String value) {
        this.gitHubAuthId = value;
    }

    /**
     * Gets the value of the triggerPhrase property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTriggerPhrase() {
        return triggerPhrase;
    }

    /**
     * Sets the value of the triggerPhrase property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTriggerPhrase(String value) {
        this.triggerPhrase = value;
    }

    /**
     * Gets the value of the skipBuildPhrase property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSkipBuildPhrase() {
        return skipBuildPhrase;
    }

    /**
     * Sets the value of the skipBuildPhrase property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSkipBuildPhrase(String value) {
        this.skipBuildPhrase = value;
    }

    /**
     * Gets the value of the blackListCommitAuthor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBlackListCommitAuthor() {
        return blackListCommitAuthor;
    }

    /**
     * Sets the value of the blackListCommitAuthor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBlackListCommitAuthor(String value) {
        this.blackListCommitAuthor = value;
    }

    /**
     * Gets the value of the blackListLabels property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBlackListLabels() {
        return blackListLabels;
    }

    /**
     * Sets the value of the blackListLabels property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBlackListLabels(String value) {
        this.blackListLabels = value;
    }

    /**
     * Gets the value of the whiteListLabels property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getWhiteListLabels() {
        return whiteListLabels;
    }

    /**
     * Sets the value of the whiteListLabels property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWhiteListLabels(String value) {
        this.whiteListLabels = value;
    }

    /**
     * Gets the value of the includedRegions property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIncludedRegions() {
        return includedRegions;
    }

    /**
     * Sets the value of the includedRegions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIncludedRegions(String value) {
        this.includedRegions = value;
    }

    /**
     * Gets the value of the excludedRegions property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExcludedRegions() {
        return excludedRegions;
    }

    /**
     * Sets the value of the excludedRegions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExcludedRegions(String value) {
        this.excludedRegions = value;
    }

    /**
     * Gets the value of the extensions property.
     *
     * @return possible object is
     * {@link ExtensionsType }
     */
    public ExtensionsType getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     *
     * @param value allowed object is
     *              {@link ExtensionsType }
     */
    public void setExtensions(ExtensionsType value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the plugin property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * Sets the value of the plugin property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPlugin(String value) {
        this.plugin = value;
    }

}
