//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 01:14:19 PM IST 
//


package com.model.configurationJenkins;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commitStatusContext" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="triggeredStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startedStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="statusUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addTestResults" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatusType", propOrder = {
    "commitStatusContext",
    "triggeredStatus",
    "startedStatus",
    "statusUrl",
    "addTestResults"
})
public class OrgJenkinsciPluginsGhprbExtensionsStatusGhprbSimpleStatusType {

    @XmlElement(required = true)
    protected String commitStatusContext;
    @XmlElement(required = true)
    protected String triggeredStatus;
    @XmlElement(required = true)
    protected String startedStatus;
    @XmlElement(required = true)
    protected String statusUrl;
    @XmlElement(required = true)
    protected String addTestResults;

    /**
     * Gets the value of the commitStatusContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommitStatusContext() {
        return commitStatusContext;
    }

    /**
     * Sets the value of the commitStatusContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommitStatusContext(String value) {
        this.commitStatusContext = value;
    }

    /**
     * Gets the value of the triggeredStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTriggeredStatus() {
        return triggeredStatus;
    }

    /**
     * Sets the value of the triggeredStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTriggeredStatus(String value) {
        this.triggeredStatus = value;
    }

    /**
     * Gets the value of the startedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartedStatus() {
        return startedStatus;
    }

    /**
     * Sets the value of the startedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartedStatus(String value) {
        this.startedStatus = value;
    }

    /**
     * Gets the value of the statusUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusUrl() {
        return statusUrl;
    }

    /**
     * Sets the value of the statusUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusUrl(String value) {
        this.statusUrl = value;
    }

    /**
     * Gets the value of the addTestResults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddTestResults() {
        return addTestResults;
    }

    /**
     * Sets the value of the addTestResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddTestResults(String value) {
        this.addTestResults = value;
    }

}
