//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 01:14:19 PM IST 
//


package com.model.configurationJenkins;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for projectType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="projectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="keepDependencies" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="properties" type="{}propertiesType"/>
 *         &lt;element name="scm" type="{}scmType"/>
 *         &lt;element name="canRoam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="disabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blockBuildWhenDownstreamBuilding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="blockBuildWhenUpstreamBuilding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="triggers" type="{}triggersType"/>
 *         &lt;element name="concurrentBuild" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="builders" type="{}buildersType"/>
 *         &lt;element name="publishers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="buildWrappers" type="{}buildWrappersType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "projectType", propOrder = {
        "actions",
        "description",
        "keepDependencies",
        "properties",
        "scm",
        "canRoam",
        "disabled",
        "blockBuildWhenDownstreamBuilding",
        "blockBuildWhenUpstreamBuilding",
        "triggers",
        "concurrentBuild",
        "builders",
        "publishers",
        "buildWrappers"
})
public class ProjectType {

    @XmlElement(required = true)
    protected String actions;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String keepDependencies;
    @XmlElement(required = true)
    protected PropertiesType properties;
    @XmlElement(required = true)
    protected ScmType scm;
    @XmlElement(required = true)
    protected String canRoam;
    @XmlElement(required = true)
    protected String disabled;
    @XmlElement(required = true)
    protected String blockBuildWhenDownstreamBuilding;
    @XmlElement(required = true)
    protected String blockBuildWhenUpstreamBuilding;
    @XmlElement(required = true)
    protected TriggersType triggers;
    @XmlElement(required = true)
    protected String concurrentBuild;
    @XmlElement(required = true)
    protected BuildersType builders;
    @XmlElement(required = true)
    protected String publishers;
    @XmlElement(required = true)
    protected BuildWrappersType buildWrappers;

    /**
     * Gets the value of the actions property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getActions() {
        return actions;
    }

    /**
     * Sets the value of the actions property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setActions(String value) {
        this.actions = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the keepDependencies property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKeepDependencies() {
        return keepDependencies;
    }

    /**
     * Sets the value of the keepDependencies property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKeepDependencies(String value) {
        this.keepDependencies = value;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     * {@link PropertiesType }
     */
    public PropertiesType getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     *              {@link PropertiesType }
     */
    public void setProperties(PropertiesType value) {
        this.properties = value;
    }

    /**
     * Gets the value of the scm property.
     *
     * @return possible object is
     * {@link ScmType }
     */
    public ScmType getScm() {
        return scm;
    }

    /**
     * Sets the value of the scm property.
     *
     * @param value allowed object is
     *              {@link ScmType }
     */
    public void setScm(ScmType value) {
        this.scm = value;
    }

    /**
     * Gets the value of the canRoam property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCanRoam() {
        return canRoam;
    }

    /**
     * Sets the value of the canRoam property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCanRoam(String value) {
        this.canRoam = value;
    }

    /**
     * Gets the value of the disabled property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDisabled() {
        return disabled;
    }

    /**
     * Sets the value of the disabled property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDisabled(String value) {
        this.disabled = value;
    }

    /**
     * Gets the value of the blockBuildWhenDownstreamBuilding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBlockBuildWhenDownstreamBuilding() {
        return blockBuildWhenDownstreamBuilding;
    }

    /**
     * Sets the value of the blockBuildWhenDownstreamBuilding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBlockBuildWhenDownstreamBuilding(String value) {
        this.blockBuildWhenDownstreamBuilding = value;
    }

    /**
     * Gets the value of the blockBuildWhenUpstreamBuilding property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBlockBuildWhenUpstreamBuilding() {
        return blockBuildWhenUpstreamBuilding;
    }

    /**
     * Sets the value of the blockBuildWhenUpstreamBuilding property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBlockBuildWhenUpstreamBuilding(String value) {
        this.blockBuildWhenUpstreamBuilding = value;
    }

    /**
     * Gets the value of the triggers property.
     *
     * @return possible object is
     * {@link TriggersType }
     */
    public TriggersType getTriggers() {
        return triggers;
    }

    /**
     * Sets the value of the triggers property.
     *
     * @param value allowed object is
     *              {@link TriggersType }
     */
    public void setTriggers(TriggersType value) {
        this.triggers = value;
    }

    /**
     * Gets the value of the concurrentBuild property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConcurrentBuild() {
        return concurrentBuild;
    }

    /**
     * Sets the value of the concurrentBuild property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConcurrentBuild(String value) {
        this.concurrentBuild = value;
    }

    /**
     * Gets the value of the builders property.
     *
     * @return possible object is
     * {@link BuildersType }
     */
    public BuildersType getBuilders() {
        return builders;
    }

    /**
     * Sets the value of the builders property.
     *
     * @param value allowed object is
     *              {@link BuildersType }
     */
    public void setBuilders(BuildersType value) {
        this.builders = value;
    }

    /**
     * Gets the value of the publishers property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPublishers() {
        return publishers;
    }

    /**
     * Sets the value of the publishers property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPublishers(String value) {
        this.publishers = value;
    }

    /**
     * Gets the value of the buildWrappers property.
     *
     * @return possible object is
     * {@link BuildWrappersType }
     */
    public BuildWrappersType getBuildWrappers() {
        return buildWrappers;
    }

    /**
     * Sets the value of the buildWrappers property.
     *
     * @param value allowed object is
     *              {@link BuildWrappersType }
     */
    public void setBuildWrappers(BuildWrappersType value) {
        this.buildWrappers = value;
    }

}
