//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.20 at 01:14:19 PM IST 
//


package com.model.configurationJenkins;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertiesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="propertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="com.coravy.hudson.plugins.github.GithubProjectProperty" type="{}com.coravy.hudson.plugins.github.GithubProjectPropertyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "propertiesType", propOrder = {
        "comCoravyHudsonPluginsGithubGithubProjectProperty"
})
public class PropertiesType {

    @XmlElement(name = "com.coravy.hudson.plugins.github.GithubProjectProperty", required = true)
    protected ComCoravyHudsonPluginsGithubGithubProjectPropertyType comCoravyHudsonPluginsGithubGithubProjectProperty;

    /**
     * Gets the value of the comCoravyHudsonPluginsGithubGithubProjectProperty property.
     *
     * @return possible object is
     * {@link ComCoravyHudsonPluginsGithubGithubProjectPropertyType }
     */
    public ComCoravyHudsonPluginsGithubGithubProjectPropertyType getComCoravyHudsonPluginsGithubGithubProjectProperty() {
        return comCoravyHudsonPluginsGithubGithubProjectProperty;
    }

    /**
     * Sets the value of the comCoravyHudsonPluginsGithubGithubProjectProperty property.
     *
     * @param value allowed object is
     *              {@link ComCoravyHudsonPluginsGithubGithubProjectPropertyType }
     */
    public void setComCoravyHudsonPluginsGithubGithubProjectProperty(ComCoravyHudsonPluginsGithubGithubProjectPropertyType value) {
        this.comCoravyHudsonPluginsGithubGithubProjectProperty = value;
    }

}
