//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.10 at 12:26:01 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.sforce.com/2006/04/metadata", elementFormDefault =
        javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.model;
